# == Schema Information
#
# Table name: reads
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  book_id    :bigint           not null
#  meeting_id :bigint           not null
#
# Indexes
#
#  index_reads_on_book_id     (book_id)
#  index_reads_on_meeting_id  (meeting_id)
#
# Foreign Keys
#
#  fk_rails_...  (book_id => books.id)
#  fk_rails_...  (meeting_id => meetings.id)
#
class Read < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :book
  belongs_to :meeting
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
